// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SshServiceClient is the client API for SshService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SshServiceClient interface {
	RunCommand(ctx context.Context, in *SshCommand, opts ...grpc.CallOption) (*SshResponse, error)
}

type sshServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSshServiceClient(cc grpc.ClientConnInterface) SshServiceClient {
	return &sshServiceClient{cc}
}

func (c *sshServiceClient) RunCommand(ctx context.Context, in *SshCommand, opts ...grpc.CallOption) (*SshResponse, error) {
	out := new(SshResponse)
	err := c.cc.Invoke(ctx, "/SshService/RunCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SshServiceServer is the server API for SshService service.
// All implementations must embed UnimplementedSshServiceServer
// for forward compatibility
type SshServiceServer interface {
	RunCommand(context.Context, *SshCommand) (*SshResponse, error)
	mustEmbedUnimplementedSshServiceServer()
}

// UnimplementedSshServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSshServiceServer struct {
}

func (UnimplementedSshServiceServer) RunCommand(context.Context, *SshCommand) (*SshResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunCommand not implemented")
}
func (UnimplementedSshServiceServer) mustEmbedUnimplementedSshServiceServer() {}

// UnsafeSshServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SshServiceServer will
// result in compilation errors.
type UnsafeSshServiceServer interface {
	mustEmbedUnimplementedSshServiceServer()
}

func RegisterSshServiceServer(s grpc.ServiceRegistrar, srv SshServiceServer) {
	s.RegisterService(&SshService_ServiceDesc, srv)
}

func _SshService_RunCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SshCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SshServiceServer).RunCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SshService/RunCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SshServiceServer).RunCommand(ctx, req.(*SshCommand))
	}
	return interceptor(ctx, in, info, handler)
}

// SshService_ServiceDesc is the grpc.ServiceDesc for SshService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SshService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SshService",
	HandlerType: (*SshServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunCommand",
			Handler:    _SshService_RunCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ssht.proto",
}
