// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: ssht.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SshCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Host     string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Command  string `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`
}

func (x *SshCommand) Reset() {
	*x = SshCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ssht_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SshCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SshCommand) ProtoMessage() {}

func (x *SshCommand) ProtoReflect() protoreflect.Message {
	mi := &file_ssht_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SshCommand.ProtoReflect.Descriptor instead.
func (*SshCommand) Descriptor() ([]byte, []int) {
	return file_ssht_proto_rawDescGZIP(), []int{0}
}

func (x *SshCommand) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SshCommand) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *SshCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type SshResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *SshResponse) Reset() {
	*x = SshResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ssht_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SshResponse) ProtoMessage() {}

func (x *SshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ssht_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SshResponse.ProtoReflect.Descriptor instead.
func (*SshResponse) Descriptor() ([]byte, []int) {
	return file_ssht_proto_rawDescGZIP(), []int{1}
}

func (x *SshResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_ssht_proto protoreflect.FileDescriptor

var file_ssht_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x73, 0x73, 0x68, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x56, 0x0a, 0x0a,
	0x53, 0x73, 0x68, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x22, 0x29, 0x0a, 0x0b, 0x53, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32,
	0x35, 0x0a, 0x0a, 0x53, 0x73, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x27, 0x0a,
	0x0a, 0x52, 0x75, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x0b, 0x2e, 0x53, 0x73,
	0x68, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x1a, 0x0c, 0x2e, 0x53, 0x73, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x61, 0x6b, 0x79, 0x61, 0x7a, 0x69, 0x2f, 0x72, 0x70, 0x63,
	0x2d, 0x73, 0x73, 0x68, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ssht_proto_rawDescOnce sync.Once
	file_ssht_proto_rawDescData = file_ssht_proto_rawDesc
)

func file_ssht_proto_rawDescGZIP() []byte {
	file_ssht_proto_rawDescOnce.Do(func() {
		file_ssht_proto_rawDescData = protoimpl.X.CompressGZIP(file_ssht_proto_rawDescData)
	})
	return file_ssht_proto_rawDescData
}

var file_ssht_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ssht_proto_goTypes = []interface{}{
	(*SshCommand)(nil),  // 0: SshCommand
	(*SshResponse)(nil), // 1: SshResponse
}
var file_ssht_proto_depIdxs = []int32{
	0, // 0: SshService.RunCommand:input_type -> SshCommand
	1, // 1: SshService.RunCommand:output_type -> SshResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ssht_proto_init() }
func file_ssht_proto_init() {
	if File_ssht_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ssht_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SshCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ssht_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SshResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ssht_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ssht_proto_goTypes,
		DependencyIndexes: file_ssht_proto_depIdxs,
		MessageInfos:      file_ssht_proto_msgTypes,
	}.Build()
	File_ssht_proto = out.File
	file_ssht_proto_rawDesc = nil
	file_ssht_proto_goTypes = nil
	file_ssht_proto_depIdxs = nil
}
